- name: update-rc.d prometheus
  become: true
  command: update-rc.d {{ prometheus_service_name }} defaults

- name: restart prometheus
  become: true
  service:
      name: prometheus
      state: restarted

